name: Workflow 7

on:
  repository_dispatch:
    types: [trigger-workflow-7]

jobs:
  trigger-next:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Workflow 8
        run: |
          curl -X POST -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/dispatches \
            -d '{"event_type":"trigger-workflow-8"}'
